spring:
  profiles.active: local
---
server:
  port: 8881
spring:
  profiles: local
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  db_student:
    url: jdbc:mysql://127.0.0.1:3306/%s?autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    max-active: 30
    min-idle: 2
    validation-query: SELECT 1
    test-on-borrow: true
    test-while-idle: true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    pool:
      max-idle: 5
      min-idle: 5
      max-active: 20
      max-wait: 5000

mybatis:
  config-location: classpath:mybatis-config.xml




